[config]
name = Space Ranger
version = 1.0
description = 2D side-scrolling space shooter
authors = abhishek-b-mishra-1

[pygbag]
# disable sound subsystem to avoid browser autoplay policy errors
snd = 0
